version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: makerspace_app
    restart: always
    ports:
      - "3000:3000" 
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://postgres:password@database:5432/msykmembershipdb" 
    depends_on:
      - database 

  database:
    image: postgres:15 
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: new_password
      POSTGRES_DB: msykmembershipdb
    ports:
      - "5434:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data 

volumes:
  db_data:
